stages:
  - plan
  - apply
  - deploy

variables:
  TF_ROOT: "."

plan:
  stage: plan
  image: hashicorp/terraform:1.8
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  image: hashicorp/terraform:1.8
  script:
    - terraform apply -auto-approve tfplan

deploy:
  stage: deploy
  image: alpine/helm:3.14.2
  script:
    - helm upgrade --install gradyent-app ./helm-chart